all: poisson eigenvalue cahn-hilliard

poisson:
	python3 demo_poisson.py

nonlinear_poisson:
	python3 demo_nonlinear_poisson.py

eigenvalue:
	python3 demo_eigenvalue.py

cahn-hilliard:
	python3 demo_cahn-hilliard.py
