all: ft01 ft02 ft03 ft04 ft05 ft06 ft07 ft08 ft09 ft10 ft11 ft12

ft01:
	python3 ft01_poisson.py

ft02:
	python3 ft02_poisson_membrane.py

ft03:
	python3 ft03_heat.py

ft04:
	python3 ft04_heat_gaussian.py

ft05:
	python3 ft05_poisson_nonlinear.py
